config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resource :like
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  after_create_commit { broadcast_prepend_to "tweets" }
  after_update_commit { broadcast_replace_to "tweets" }
  after_destroy_commit { broadcast_remove_to "tweets" }

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @tweet.increment! :likes
    @tweet.update(updated_at: Time.current)
    redirect_to @tweet
  end

  private
  
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %w[ show edit update destroy ]

  def index
    @tweet = Tweet.new
    @tweets = Tweet.order(created_at: :desc).limit(100)
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: "Tweet was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@tweet, partial: "tweets/form", locals: { tweet: @tweet }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
    end
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body, :likes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hotwire
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    .container.mt-5
      .row
        .col-lg-3.col-md-2
        .col-lg-6.pl-lg-0.col-md-8.pl-md-0
          - if notice
            .alert.alert-info= notice
          - if alert
            .alert.alert-warning= alert
          = yield
        .col-lg-3.col-md-2

app/views/tweets/_form.html.haml
= form_with(model: tweet, id: dom_id(tweet)) do |form|
  - if tweet.errors.any?
    .alert.alert-warning
      - tweet.errors.each do |error|
        = error.full_message
  .form-group
    = form.text_area :body, class: "form-control bg-light", rows: 3
  .form-group.float-left
    = form.submit 'Send Tweet', class: "btn btn-primary"

app/views/tweets/_tweet.html.haml
= turbo_frame_tag dom_id(tweet) do
  .card.mb-3
    .card-body
      %p.text-muted.small Posted #{time_ago_in_words(tweet.created_at)} ago • Updated #{time_ago_in_words(tweet.updated_at)} ago
      %p.mb-1= tweet.body
    .card-footer
      .float-right
        = link_to 'Edit', edit_tweet_path(tweet), class: "ml-2 btn btn-primary btn-sm"
        = link_to 'Delete', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "ml-2 btn btn-danger btn-sm"
      = button_to "Like", tweet_like_path(tweet), method: :post, class: "btn btn-primary btn-sm mr-2 float-left"
      .likes.mt-1
        - unless tweet.likes == nil
          .text-muted #{tweet.likes} Likes
        - else
          .text-muted No Likes Yet
      .clearfix

app/views/tweets/edit.html.haml
%h1 Editing Tweet

= turbo_frame_tag dom_id(@tweet) do
  .card.mb-3
    .card-body.pb-0
      = render 'form', tweet: @tweet
      = link_to "Cancel", @tweet, class: "btn btn-secondary ml-2"

app/views/tweets/index.html.haml
= turbo_stream_from "tweets"
%h1.text-dark 🍭 Tweeter
%p.mb-0
  %span= link_to "Hotwire", "https://hotwire.dev"
  %span Unofficial Technology Demo
%p.small.mb-0
  %span Based on the
  %span= link_to "tutorial", "https://www.youtube.com/watch?v=Qp6sxgjA-xY"
  %span by Chris Oliver / GoRails. Find
  %span= link_to "source code", "https://github.com/iraszl/hotwire"
  %span on Github.
%p.small Hint: Open two browser windows. Change in one reflects in the other without page reload.
%hr
%p What's on your mind?
= turbo_frame_tag "tweet_form" do
  = render 'form', tweet: @tweet
.clearfix
%hr
= turbo_frame_tag "tweets" do
  -# = render partial: "tweet", locals: {tweets: @tweets}
  = render @tweets

app/views/tweets/new.html.haml
%h1 New Tweet
= render 'form', tweet: @tweet
= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
= turbo_frame_tag dom_id(@tweet) do
  = render @tweet